### ISSUE TITLE
Update dependecies

### ISSUE THREAD

**Issue by brookman** [vjames19/kotlin-futures#6]
Upgrade the dependencies to the newest Kotlin version. Current dependencies:

+--- com.github.vjames19.kotlin-futures:kotlin-futures-jdk8:0.4.0
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jre8:1.1.2-5
|         \--- org.jetbrains.kotlin:kotlin-stdlib-jre7:1.1.2-5
|              \--- org.jetbrains.kotlin:kotlin-stdlib:1.1.2-5

ToDo:
1. Update Kotlin dependency to version 1.2.51
2. Change "jre" dependencies to "jdk" ("jre" seems to be deprecated).

Great lib, thanks!

**Comment by vjames19** [comment]
Hi, I will be able to update this next Sunday. As soon as it is done I will
update you.

**Comment by vjames19** [comment]
@brookman Just updated the library.

Let me know if there is anything else you would like to see added to the library.
